# Site settings
title: EY Code Style Guide
description: A mostly reasonable approach to general code style
baseurl: "/javascript"
url: "https://cloudx-labs.github.io"

# Repository settings
repository: cloudx-labs/javascript

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Navigation
navigation:
  - title: JavaScript
    url: /javascript/js/
  - title: React
    url: /javascript/react/
  - title: Functional Programming
    url: /javascript/fp/
  - title: Library Usage
    url: /javascript/lib/

# GitHub Pages settings
github:
  repository_nwo: cloudx-labs/javascript
